######################################################################
# Automatically generated by qmake (3.1) Mon Sep 15 13:46:10 2025
######################################################################

TEMPLATE = app
TARGET = virtual_library
INCLUDEPATH += .
QT += widgets

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += JsonFile.h \
           gui/EditView.h \
           gui/AddView.h \
           gui/LibraryView.h \
           gui/MediaView.h \
           gui/MediaWidget.h \
           gui/ViewManager.h \
           model/AbstractMedia.h \
           model/Article.h \
           model/Book.h \
           model/Film.h \
           model/MediaVisitor.h \
           model/Utilities.h
SOURCES += JsonFile.cpp \
           main.cpp \
           gui/EditView.cpp \
           gui/AddView.cpp \
           gui/LibraryView.cpp \
           gui/MediaView.cpp \
           gui/MediaWidget.cpp \
           gui/ViewManager.cpp \
           model/AbstractMedia.cpp \
           model/Article.cpp \
           model/Book.cpp \
           model/Film.cpp \
           model/Utilities.cpp
